import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import  Header  from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";

// the fonts which we are going to use in the project
const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: "Sensai - AI Career Coach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      baseTheme: dark
    }}>

      {/* below suppressHydrationWarning is an error handler used to manage the error */}
      <html lang="en" suppressHydrationWarning>

        <body className={` ${inter.className} `} >
          <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem
              disableTransitionOnChange
            >

              {/* This is our header */}
              <Header/>

              <main className="min-h-screen"> {children} </main>
              <Toaster richColors />

              {/* This is our footer */}
              <footer className="bg-muted/50 py-12">
                <div className="container mx-auto px-4 text-center text-gray-200">
                  <p> Made with ❤️ by Ariba Ansari & Kashif Siddique </p> 
                </div>
              </footer>
            </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
};
